# Generated by Django 5.0 on 2024-06-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='work_type',
        ),
    ]
