# Generated by Django 5.0 on 2024-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_worker_id_card_remove_worker_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
            ],
        ),
    ]
