# Generated by Django 5.0 on 2024-06-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_home',
            new_name='customer_info',
        ),
    ]
