# Generated by Django 5.0 on 2024-06-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_customer_home_customer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ac_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=25)),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
