# Generated by Django 5.0 on 2024-06-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ac_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac_info',
            name='fee',
        ),
    ]
