# Generated by Django 5.0 on 2024-06-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_ac_info_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='fridge_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=25)),
            ],
        ),
    ]
