# Generated by Django 5.0 on 2024-06-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
    ]
