# Generated by Django 5.0 on 2024-06-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_user_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('contact', models.IntegerField(max_length=10)),
                ('item', models.CharField(max_length=25)),
                ('service', models.CharField(max_length=25)),
                ('adresee', models.TextField(max_length=500)),
            ],
        ),
    ]
