# Generated by Django 5.0 on 2024-08-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_worker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='cusr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta', models.BooleanField(default=False)),
            ],
        ),
    ]
