# Generated by Django 5.0 on 2024-08-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cusr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cusr',
        ),
        migrations.AddField(
            model_name='conf',
            name='sta',
            field=models.BooleanField(default=False),
        ),
    ]
