# Generated by Django 5.0 on 2024-08-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_cusr_conf_sta'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
