# Generated by Django 5.0 on 2024-08-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_woekstatus_remove_worker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_in',
            name='username',
        ),
    ]
