# Generated by Django 5.0 on 2024-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_user_in_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='city',
            field=models.CharField(default='kochi', max_length=25),
        ),
    ]
