# Generated by Django 5.0 on 2024-08-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_conf_wor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='crea',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-03'),
            preserve_default=False,
        ),
    ]
